name: 'Run Action'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-action:
    name: Run action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run action
        uses: ./
        id: action
        with:
          url: https://reinhold.is
          runs: 2
          strategy: both
          comment: update
          threshold: 95
          compareUrl: https://developers.google.com
